# Generated by Django 5.0.6 on 2024-07-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monumentimage',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monumentimage',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
